config/routes.rb
Rails.application.routes.draw do
  get 'rangers/racers'

  resources :carproducts
  resources :carcategories
  get 'home/welcome'
root to: 'home#welcome'
  devise_for :users
  
devise_scope :user do
  get '/users/sign_out', to: 'devise/sessions#destroy'
end
 get 'display/:id'=>'carcategories#display', as: :display
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.role?
          can :manage, :all
        else
          can :read, :all
        end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carcategory.rb
class Carcategory < ApplicationRecord
  has_many :carproducts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/carproduct.rb
class Carproduct < ApplicationRecord
  belongs_to :carcategory
  has_attached_file :avatar, styles: { medium: "30x30>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
def self.role?
self.role
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/carcategories_controller.rb
class CarcategoriesController < ApplicationController
  before_action :set_carcategory, only: [:show, :edit, :update, :destroy]

  # GET /carcategories
  # GET /carcategories.json
  def index
    @carcategories = Carcategory.all
  end

  # GET /carcategories/1
  # GET /carcategories/1.json
  def show
  end

  # GET /carcategories/new
  def new
    @carcategory = Carcategory.new
  end
  def display
  	@category=Carcategory.find(params[:id])
        @products=@category.carproducts
  end
  # GET /carcategories/1/edit
  def edit
  end

  # POST /carcategories
  # POST /carcategories.json
  def create
    @carcategory = Carcategory.new(carcategory_params)

    respond_to do |format|
      if @carcategory.save
        format.html { redirect_to @carcategory, notice: 'Carcategory was successfully created.' }
        format.json { render :show, status: :created, location: @carcategory }
      else
        format.html { render :new }
        format.json { render json: @carcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carcategories/1
  # PATCH/PUT /carcategories/1.json
  def update
    respond_to do |format|
      if @carcategory.update(carcategory_params)
        format.html { redirect_to @carcategory, notice: 'Carcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @carcategory }
      else
        format.html { render :edit }
        format.json { render json: @carcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carcategories/1
  # DELETE /carcategories/1.json
  def destroy
    @carcategory.destroy
    respond_to do |format|
      format.html { redirect_to carcategories_url, notice: 'Carcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carcategory
      @carcategory = Carcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carcategory_params
      params.require(:carcategory).permit(:name, :description, :avatar)
    end
end

app/controllers/carproducts_controller.rb
class CarproductsController < ApplicationController
  before_action :set_carproduct, only: [:show, :edit, :update, :destroy]
   before_action :get_categories, only: [:new, :edit]
  # GET /carproducts
  # GET /carproducts.json
  def index
    @carproducts = Carproduct.all
  end

  # GET /carproducts/1
  # GET /carproducts/1.json
  def show
  end

  # GET /carproducts/new
  def new
    @carproduct = Carproduct.new
  end

  # GET /carproducts/1/edit
  def edit
  end

  # POST /carproducts
  # POST /carproducts.json
  def create
    @carproduct = Carproduct.new(carproduct_params)

    respond_to do |format|
      if @carproduct.save
        format.html { redirect_to @carproduct, notice: 'Carproduct was successfully created.' }
        format.json { render :show, status: :created, location: @carproduct }
      else
        format.html { render :new }
        format.json { render json: @carproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carproducts/1
  # PATCH/PUT /carproducts/1.json
  def update
    respond_to do |format|
      if @carproduct.update(carproduct_params)
        format.html { redirect_to @carproduct, notice: 'Carproduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @carproduct }
      else
        format.html { render :edit }
        format.json { render json: @carproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carproducts/1
  # DELETE /carproducts/1.json
  def destroy
    @carproduct.destroy
    respond_to do |format|
      format.html { redirect_to carproducts_url, notice: 'Carproduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carproduct
      @carproduct = Carproduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carproduct_params
      params.require(:carproduct).permit(:name, :model, :fueltype, :price, :carcategory_id, :avatar)
    end
    def get_categories
	@carcategories = Carcategory.all.collect{|i| [i.name , i.id]} 
    end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/rangers_controller.rb
class RangersController < ApplicationController
  def racers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carcategories_helper.rb
module CarcategoriesHelper
end

app/helpers/carproducts_helper.rb
module CarproductsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rangers_helper.rb
module RangersHelper
end

app/views/carcategories/_form.html.erb
<%= form_with(model: carcategory, local: true, html: { multipart: true }) do |form| %>
  <% if carcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carcategory.errors.count, "error") %> prohibited this carcategory from being saved:</h2>

      <ul>
      <% carcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :carcategory_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :carcategory_description %>
  </div>

<div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, id: :carcategory_avatar%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carcategories/display.html.erb
<h1>Available products</h1>
<% @products.each{|p|%>
<%=p.name%><br>
<%=p.model%><br>
<%=p.fueltype%><br>
<%=p.price%><br>
<%= image_tag p.avatar.url{:medium} %>
<%}%>

app/views/carcategories/edit.html.erb
<h1>Editing Carcategory</h1>

<%= render 'form', carcategory: @carcategory %>

<%= link_to 'Show', @carcategory %> |
<%= link_to 'Back', carcategories_path %>

app/views/carcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carcategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carcategories.each do |carcategory| %>
      <tr>
        <td><%= carcategory.name %></td>
        <td><%= carcategory.description %></td>
        <td><%= image_tag carcategory.avatar.url{:medium} %></td>
       
        <td><%= link_to 'Show', display_path(carcategory.id) %></td>
        <% if can? :create, carcategory %>
        <td><%= link_to 'Edit', edit_carcategory_path(carcategory) %></td>
        <td><%= link_to 'Destroy', carcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @carcategory %>
<%= link_to 'New Carcategory', new_carcategory_path %>
<%end%>

app/views/carcategories/new.html.erb
<h1>New Carcategory</h1>

<%= render 'form', carcategory: @carcategory %>

<%= link_to 'Back', carcategories_path %>

app/views/carcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @carcategory.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @carcategory.description %>
</p>
<p>
<%= image_tag @carcategory.avatar.url{:medium}%>
</p>
<%= link_to 'Edit', edit_carcategory_path(@carcategory) %> |
<%= link_to 'Back', carcategories_path %>

app/views/carproducts/_form.html.erb
<%= form_with(model: carproduct, local: true, html: { multipart: true }) do |form| %>
  <% if carproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carproduct.errors.count, "error") %> prohibited this carproduct from being saved:</h2>

      <ul>
      <% carproduct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :carproduct_name %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :carproduct_model %>
  </div>

  <div class="field">
    <%= form.label :fueltype %>
    <%= form.text_field :fueltype, id: :carproduct_fueltype %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :carproduct_price %>
  </div>

  <div class="field">
    <%= form.label :carcategory_id %>
    <%= form.select :carcategory_id, @carcategories %>
  </div>
   <div class="field">
    <%= form.label :image %>
    <%= form.file_field :avatar, id: :carproduct_avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carproducts/edit.html.erb
<h1>Editing Carproduct</h1>

<%= render 'form', carproduct: @carproduct %>

<%= link_to 'Show', @carproduct %> |
<%= link_to 'Back', carproducts_path %>

app/views/carproducts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="padding-left:550px">Carproducts</h1>
<br>
<br>

<table class="table table-border">
  <thead>
    <tr>
      <th>Name</th>
      <th>Model</th>
      <th>Fueltype</th>
      <th>Price</th>
      <th>Carcategory</th>
      <th style="padding-left:150px">Car Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carproducts.each do |carproduct| %>
      <tr>
        <td><%= carproduct.name %></td>
        <td><%= carproduct.model %></td>
        <td><%= carproduct.fueltype %></td>
        <td><%= carproduct.price %></td>
        <td><%= carproduct.carcategory.name %></td>
        <td><%= image_tag carproduct.avatar.url{:medium} %></td>
        <% if can? :create, carproduct %>
        <td><%= link_to 'Show', carproduct %></td>
        <td><%= link_to 'Edit', edit_carproduct_path(carproduct) %></td>
        <td><%= link_to 'Destroy', carproduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%end%>      
</tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @carproduct %>
<%= link_to 'New Carproduct', new_carproduct_path %>
<%end%>

app/views/carproducts/new.html.erb
<h1>New Carproduct</h1>

<%= render 'form', carproduct: @carproduct %>

<%= link_to 'Back', carproducts_path %>

app/views/carproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @carproduct.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @carproduct.model %>
</p>

<p>
  <strong>Fueltype:</strong>
  <%= @carproduct.fueltype %>
</p>

<p>
  <strong>Price:</strong>
  <%= @carproduct.price %>
</p>

<p>
  <strong>Carcategory:</strong>
  <%= @carproduct.carcategory.name %>
</p>
<p>
<%= image_tag @carproduct.avatar.url{:medium} %>
</p>
<%= link_to 'Edit', edit_carproduct_path(@carproduct) %> |
<%= link_to 'Back', carproducts_path %>

app/views/home/_footer.html.erb
    <footer>
     <div class="container">
       <div class="row">
       
                <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                    <ul class="adress">
                         <span>Address</span>    
                         <li>
                            <p>BB&T Corporation.
				200 West Second Street.
				Winston-Salem, NC 27101.
				800-BANK-BBT (800-226-5228)
			    </p>
                          </li>
                               
                          
                     </ul>
                </div>
                
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <ul class="contact">
                         <span>Contact</span>    
                         <li>
                            <p style="color:white">+6195847135143</p>
                          </li>
                           <li>
                            <p style="color:white">nikhils688.ns@gmail.com</p>
                          </li>
                               
                          
                    </ul>
                </div>
           
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                   <ul class="social">
                              <span>Social</span>    
                               <li>
                                    <a href="https://www.facebook.com/BBToyz"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                               </li>
                              
                               <li>
                                    <a href="https://git-scm.com/" style="padding-left:30px"><i class="glyphicon glyphicon-briefcase"></i></a>
                               </li>
                                
                               
                     </ul>
                </div>
           
           
           </div> 
        </div>
    </footer>
	

app/views/home/_header.html.erb
<div class="container-fluid">
	<div class="row">
			<div class="back">
				<div id="f1">
					<div class="col-sm-5">					
					      <img src="/assets/logo.jpg" alt="Smiley face" height="200" width="160" id="logo">
                                         </div> 	
                                         <div class="col-sm-6">
				  		<h1 style="color:red">Explore The Racer In You</h1>
					</div>
				</div>
			</div>
	</div>
</div>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Welcome</a>
    </div>
<div class="logout">
<ul class="nav navbar-nav navbar-right">
     
      <li><a href=<%= destroy_user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
</div>
<div class="nalist">
    <ul class="nav navbar-nav">
      <li><a href="/home/welcome">Home</a></li>
      <li><a href="/rangers/racers">Racers</a></li>
      <li><a href="#">View Tweets</a></li>
      <li><a href="#">About Us</a></li>
    </ul>
</div>

 </div>
</nav>

app/views/home/welcome.html.erb
<%= render "header" %>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img class="first-slide" src="/assets/i1c.jpg">
                </div>
                <div class="item">
                    <img class="second-slide" src="/assets/i2c.jpg">
                </div>
                <div class="item">
                    <img class="third-slide" src="/assets/i3c.jpg">
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div><!-- /.carousel -->
<div class="container-fluid text-center">
  <h2>SERVICES</h2>
  <h4>What we offer</h4>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off"></span>
      <h4>POWER</h4>
      <p>Believe The Racer in You</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart"></span>
      <h4>LOVE</h4>
      <p>Engine is the Love</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock"></span>
      <h4>JOB DONE</h4>
      <p>Gurantee Services And Believes</p>
    </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf"></span>
      <h4>GREEN</h4>
      <p>Believe In Natural Technology</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate"></span>
      <h4>CERTIFIED</h4>
      <p>World Knows Us</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-wrench"></span>
      <h4 style="color:#303030;">HARD WORK</h4>
      <p>Variety of The Trainers</p>
    </div>
  </div>
</div>


<div >
<% if current_user && current_user.role?%>
<div class="left-image">
<%= link_to image_tag("b2.jpg", :alt => "home image", :width => 650, :height => 400) , carproducts_path%>
<div class="centered"><div class="panel panel-info">Manage Brands</div></div>
</div>
<div class="right-image">
<%= link_to image_tag("b3.jpg", :alt => "home image", :width => 630, :height => 400) , carcategories_path%>
<div class="centered1"><div class="panel panel-info">Manage Cars</div></div>
</div>
<br>
</div>
<div>
<% else %>
<center>
<div class="apple">
<%= link_to "View Cars In ShowRoom", carcategories_path%>
</div>
</center>
<% end %>
</div>
  











<div class="container-fluid text-center bg-grey">
  <h2>Flagship</h2><br>
  <h4>What we have created</h4>
  <div class="row text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="/assets/w1.jpg" alt="Paris" width="400" height="300">
        <p><strong>Rajputana Customs</strong></p>
        <p>We Created The Garage for Dreamers</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="/assets/w2.jpg" alt="New York" width="400" height="300">
        <p><strong>GTA SanAndreas</strong></p>
        <p>First American Game Under Us</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="/assets/w3.jpg" alt="San Francisco" width="400" height="300">
        <p><strong>Mafia</strong></p>
        <p>Partner With The Leading Game Company</p>
      </div>
    </div>
  </div>
</div>

<%= render "footer" %>

app/views/layouts/_footer.html.erb
    <footer>
     <div class="container">
       <div class="row">
       
                <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                    <ul class="adress">
                         <span>Address</span>    
                         <li>
                            <p>BB&T Corporation.
				200 West Second Street.
				Winston-Salem, NC 27101.
				800-BANK-BBT (800-226-5228)
			    </p>
                          </li>
                               
                          
                     </ul>
                </div>
                
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <ul class="contact">
                         <span>Contact</span>    
                         <li>
                            <p style="color:white">+6195847135143</p>
                          </li>
                           <li>
                            <p style="color:white">nikhils688.ns@gmail.com</p>
                          </li>
                               
                          
                    </ul>
                </div>
           
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                   <ul class="social">
                              <span>Social</span>    
                               <li>
                                    <a href="https://www.facebook.com/BBToyz"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                               </li>
                              
                               <li>
                                    <a href="https://git-scm.com/" style="padding-left:30px"><i class="glyphicon glyphicon-briefcase"></i></a>
                               </li>
                                
                               
                     </ul>
                </div>
           
           
           </div> 
        </div>
    </footer>
	

app/views/layouts/_header.html.erb
<div class="container-fluid">
	<div class="row">
			<div class="back">
				<div id="f1">
					<div class="col-sm-5">					
					      <img src="/assets/logo.jpg" alt="Smiley face" height="200" width="160" id="logo">
                                         </div> 	
                                         <div class="col-sm-6">
				  		<h1 style="color:red">Explore The Racer In You</h1>
					</div>
				</div>
			</div>
	</div>
</div>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Welcome</a>
    </div>
<div class="logout">
<ul class="nav navbar-nav navbar-right">
      <li><a href=<%= destroy_user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
</div>
<div class="nalist">
    <ul class="nav navbar-nav">
      <li><a href="/home/welcome">Home</a></li>
      <li><a href="/rangers/racers">Racers</a></li>
      <li><a href="#">Overview</a></li>
      <li><a href="#">About Us</a></li>
    </ul>
</div>

 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     


    <%= yield %>
  </body>
</html>

app/views/rangers/_footer.html.erb
    <footer>
     <div class="container">
       <div class="row">
       
                <div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
                    <ul class="adress">
                         <span>Address</span>    
                         <li>
                            <p>BB&T Corporation.
				200 West Second Street.
				Winston-Salem, NC 27101.
				800-BANK-BBT (800-226-5228)
			    </p>
                          </li>
                               
                          
                     </ul>
                </div>
                
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <ul class="contact">
                         <span>Contact</span>    
                         <li>
                            <p style="color:white">+6195847135143</p>
                          </li>
                           <li>
                            <p style="color:white">nikhils688.ns@gmail.com</p>
                          </li>
                               
                          
                    </ul>
                </div>
           
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                   <ul class="social">
                              <span>Social</span>    
                               <li>
                                    <a href="https://www.facebook.com/BBToyz"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                               </li>
                              
                               <li>
                                    <a href="https://git-scm.com/" style="padding-left:30px"><i class="glyphicon glyphicon-briefcase"></i></a>
                               </li>
                                
                               
                     </ul>
                </div>
           
           
           </div> 
        </div>
    </footer>
	

app/views/rangers/_header.html.erb
<div class="container-fluid">
	<div class="row">
			<div class="back">
				<div id="f1">
					<div class="col-sm-5">					
					      <img src="/assets/logo.jpg" alt="Smiley face" height="200" width="160" id="logo">
                                         </div> 	
                                         <div class="col-sm-6">
				  		<h1 style="color:red">Explore The Racer In You</h1>
					</div>
				</div>
			</div>
	</div>
</div>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Welcome</a>
    </div>
<div class="logout">
<ul class="nav navbar-nav navbar-right">
      <li><a href=<%= destroy_user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
</div>
<div class="nalist">
    <ul class="nav navbar-nav">
      <li><a href="/home/welcome">Home</a></li>
      <li><a href="/rangers/racers">Racers</a></li>
      <li><a href="#">View Tweets</a></li>
      <li><a href="#">About Us</a></li>
    </ul>
</div>

 </div>
</nav>